---
general:
  buildTool: "npm"
  jenkinsKubernetes:
    securityContext:
      runAsUser: 1000
      fsGroup: 1000
service:
  buildToolVersion: "N18"
stages:
  Build:
    mavenExecuteStaticCodeChecks: false
    npmExecuteLint: false
  Container Build:
    # that has no effect:
    stashContent: [ "buildResult" ]
    verbose: true
  Additional Unit Tests:
    npmExecuteScripts: false
  Acceptance:
    cloudFoundryDeploy: false
    npmExecuteEndToEndTests: false
  Compliance:
    sonarExecuteScan: false
  Release:
    cloudFoundryDeploy: false
    tmsUpload: false
steps:
  artifactPrepareVersion:
    versioningType: "cloud_noTag"
  cloudFoundryDeploy:
    mtaDeployParameters: "-f --version-rule ALL"

  # custom additions to make nom build work 
  buildExecute:
    npmRunScripts: [ 'cds-build' ]
    npmInstall: false

  pipelineStashFilesAfterBuild:
    stashIncludes:
      buildResult: '**/*'

  # cnbBuild config
  cnbBuild:
    dockerConfigJsonCredentialsId: docker-config
    containerRegistryUrl: concise.common.repositories.cloud.sap
    containerImageTag: latest
    multipleImages:
      - path: gen/srv
        containerImageName: susaas-images/susaas-srv
      - path: gen/api
        containerImageName: susaas-image/usaas-api
      - path: broker
        containerImageName: susaas-image/broker



    

